

import React from 'react';
import AIChartCard from '../../../../components/AIChartCard';

const TeamPerformance: React.FC = () => {
    return (
        <div className="h-full flex flex-col gap-2">
            <h2 className="text-3xl font-bold text-white">Team Performance</h2>
            <div className="flex-1 grid grid-cols-1 lg:grid-cols-2 gap-2 min-h-0">
                <AIChartCard
                    title="Deals Closed per Rep (This Quarter)"
                    prompt="Create a bar chart for deals closed by sales reps: Sarah Connor (12 deals), Kyle Reese (9 deals), Miles Dyson (7 deals), John Anderton (5 deals)."
                />
                <AIChartCard
                    title="Revenue Generated per Rep (This Quarter)"
                    prompt="Create a bar chart for revenue generated by sales reps: Sarah Connor ($210k), Kyle Reese ($155k), Miles Dyson ($120k), John Anderton ($85k)."
                />
            </div>
        </div>
    );
};

export default TeamPerformance;
